### PR TITLE
Consider Time.near when returning search results

### LINKED ISSUE #7: 'near' keyword is ignored in `attrs.Time`
`attrs.Time` allows for a `near` kwarg such that, within the range specified by `start` and `end`, only the observation nearest that time specified to `near` is returned. When passing a `Time` attr with `near`, `sunpy_soar` ignores this keyword and returns every result in the `start,end` range.

As an example,

```python
import sunpy_soar
from sunpy.net import attrs, Fido
from sunpy_soar import attrs as soar_attrs

q = Fido.search(
    attrs.Time('2021-04-21 18:03:19', end='2021-04-21 21:04:04', near='2021-04-21 19:33:41'),
    attrs.Level(2),
    attrs.Instrument('EUI'),
    soar_attrs.Identifier('EUI-FSI174-IMAGE'),
)
```
returns 48 results, not 1. A similar query to the VSO for AIA 171 data would return a single result close to '2021-04-21 19:33:41'.

This may not be a bug per se as I'm not sure if the SOAR API supports this at all so feel free to close this if that is the case.

### PR DESCRIPTION
**Pull request by wtbarnes**
Fixes #7 

This feels really hacky and the code makes me a bit ill looking at it, but it does work. 😅  

From what I can tell, post-search hooks are not a thing for full clients so I'm not sure if there is a better place to put this. The filtering inside the query_parameters iteration could be pulled into a separate function to clean things up.

### CODE REVIEW

**Comment by dstansby** [comment]
Trying to work out what to do here, and I think it's quite complicated as a mix of AND/OR queries needs to be taken into account. I think the best thing would be to implement a `QueryResponseTable.closest_result_to(t: astropy.time.Time)` method in sunpy that would let you filter any results table to get the result closest to a given time. This would be more generic and apply to results from any client.

**Comment by wtbarnes** [comment]
> Trying to work out what to do here, and I think it's quite complicated as a mix of AND/OR queries needs to be taken into account. I think the best thing would be to implement a `QueryResponseTable.closest_result_to(t: astropy.time.Time)` method in sunpy that would let you filter any results table to get the result closest to a given time. This would be more generic and apply to results from any client.

That sounds good to me. I agree there are too many cases here to consider and it makes sense to provide this functionality for other clients (that don't support it natively) as well.

**Comment by Cadair** [comment]
I am generally :-1: on filtering post-search, because while for simple clients like scraper ones it generally doesn't save much time, for complex clients like VSO, DKIST etc it can be a *lot* faster to search server side (i.e. with attrs) so we should be encouraging users to use the attrs functionality for all clients so they get the fastest searches possible.

More specifically here, the best place to add this logic would not be the search method but inside your walker. In [this](https://github.com/dstansby/sunpy-soar/blob/main/sunpy_soar/attrs.py#L38) function add some other flag somewhere (maybe by subclassing list) which you can then use later.

**Comment by wtbarnes** [comment]
I wonder if a good compromise here would be to add a `util` in `sunpy.net` that allows post-search near-time filtering that clients that don't have the option of server-side search to take advantage of. 

> More specifically here, the best place to add this logic would not be the search method but inside your walker. In this function add some other flag somewhere (maybe by subclassing list) which you can then use later.

But that option still requires each client to implement this themselves

**Comment by dstansby** [comment]
Even if the server does support it server-side, there's no reason not to implement the logic to get the nearest result in `sunpy` post-search too.

**Comment by dstansby** [comment]
Oh, but you can string together complicated sets of queries that can include multiple time attributes... hmm

**Pull request closed without merging**
